Issue8: loan table creation is done
TechUniv2018/social-credit pull request #50
Opened 2018-02-08 13:19 UTC by Nidhi1461996

2018-02-08 15:11 UTC, mrsauravsahu requested changes

2018-02-08 15:11 UTC, mrsauravsahu commented on package.json
> +    "test": "npm run testmigration",
You removed `jest` from test in the scripts section. You should run jest when `npm run testmigration` does not fail. Change it to `npm run testmigration && jest`

2018-02-08 15:11 UTC, mrsauravsahu commented on models/loans.js
> +    userID: DataTypes.INTEGER,
Should we use `userId` instead of `userID`? We have to use camel case

2018-02-08 15:11 UTC, saurav-sahu commented on migrations/20180205133032-create-loans.js
> +'use strict';
Fix eslint errors.

2018-02-08 15:11 UTC, saurav-sahu commented on migrations/20180208045308-remove-loanID-column.js
> +
Remove empty newlines.

2018-02-08 15:11 UTC, saurav-sahu commented on models/user.js
> +  const User = sequelize.define('Users', {
change `Users` to `users`.

2018-02-08 15:11 UTC, saurav-sahu commented on migrations/20180205133032-create-loans.js
> +        type: Sequelize.INTEGER
Use camel case. Please replace `loanID` with `loanId`.

2018-02-08 15:11 UTC, saurav-sahu commented on migrations/20180208045308-remove-loanID-column.js
> +    queryInterface.removeColumn('loans', 'loanID');
Camel casing.

2018-02-08 15:11 UTC, saurav-sahu commented on migrations/20180208045308-remove-loanID-column.js
> +    queryInterface.addColumn('loans', 'loanID', Sequelize.INTEGER);
Camel casing.

2018-02-08 15:41 UTC, Ghost---Shadow commented on models/loans.js
> +    userID: DataTypes.INTEGER,
`userId` is camel case

2018-02-08 15:45 UTC, Ghost---Shadow commented on models/loans.js
> +  }, {
`loanId` is in the migrations but not in the model.

2018-02-08 15:46 UTC, Ghost---Shadow commented on models/user.js
> +  const User = sequelize.define('Users', {
Also rename the file to `users.js`

2018-02-08 15:54 UTC, Ghost---Shadow commented on seeders/20180207121247-sample-loans.js
> +      userID: 1,
After changing the model and migration to `userId` dont forget to change this too.

2018-02-08 15:55 UTC, Ghost---Shadow commented on seeders/20180207121247-sample-loans.js
> +    },
`loanId` is missing.

2018-02-08 15:58 UTC, Ghost---Shadow requested changes
minor changes

2018-02-09 03:21 UTC, KshipraShetty commented on seeders/20180207121247-sample-loans.js
> +      updatedAt: new Date(),
loanId ?

2018-02-09 12:26 UTC, Nidhi1461996 commented on seeders/20180207121247-sample-loans.js
> +      userID: 1,
Yes done

2018-02-09 12:27 UTC, Nidhi1461996 commented on seeders/20180207121247-sample-loans.js
> +      updatedAt: new Date(),
We have removed the loanId column in the latest migration and hence it should not be there while seeding

2018-02-09 13:22 UTC, closed without merging