Added CONTRIBUTING.md
TechUniv2018/social-credit pull request #53
Opened 2018-02-08 15:31 UTC by Ghost---Shadow

2018-02-09 01:59 UTC, KshipraShetty commented on CONTRIBUTING.md
> +4. Create a pull request. The PR should not have any merge conflicts.
Shouldn't we include a point mentioning that it must be reviewed by atleast 3 members

2018-02-09 03:18 UTC, Ghost---Shadow commented on CONTRIBUTING.md
> +4. Create a pull request. The PR should not have any merge conflicts.
I dont know how to enforce that in github. It approves after only one review.

2018-02-10 06:35 UTC, mrsauravsahu requested changes
Add code of conduct link to readme and contributing.

2018-02-11 13:32 UTC, mrsauravsahu approved these changes

2018-02-12 05:00 UTC, merged